### ISSUE TITLE
Problem with unused library functions

### ISSUE THREAD

**Issue by hcvazquez** [Xotic750/assert-x#20]
My name is Hernan; with a group of colleagues we are conducting a research about unused code present in dependencies of JavaScript projects. We call this functions, UFF (Unused foreign functions). We found that in most projects there exist a great amount of UFF that are being included in the final bundle. 
 
In the case of assert-x (v 1.2.18) our tools detected approximately 90 unused function in dependencies. Removing those functions, the size of assert-x bundled could be reduced at least 18% (All tests passed). I’m attaching the reduced version of your project. 
[assert-x(optimized).txt](https://github.com/Xotic750/assert-x/files/671190/assert-x.optimized.txt)

 
I’ll be very grateful if you can answer me the following questions:
-Did you were aware of the existence of these unused functions in your projects?
-Do you think that this is a problem? 
-Do you think that can be useful a tool for deal with this kind of problem?

Thanks in advance.

Cheers,

**Comment by Xotic750** [comment]
Hi,

I am aware that with the current bundling, using npm and browserify, that projects contain a fair deal of unused code. Not a huge problem for me but I'm all for reducing code by removing unused code where possible, I guess that these tools will get better with time. If these tools are not being improved then yes a separate tool could be useful where it is of concern.
